AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Toy example, return image shape and size from binary data

  '
Globals:
  Function:
    Timeout: 200
    MemorySize: 128
    Environment:
      Variables:
        DUMMY_VAR: 1
Resources:
  ToyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: s3://aws-lambda-cv-binary/cbc800e6ca921bc3718de779cdb74677
      BinaryMediaTypes:
      - image~1jpg
  ToyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ToyFunction
      CodeUri: s3://aws-lambda-cv-binary/44125a92305837b055c79c194907844a
      Handler: lambda_function.lambda_handler
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/lambda
      Runtime: python3.6
      Policies:
      - AWSLambdaBasicExecutionRole
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:pillow:6
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: ToyApi
            Path: /{proxy+}
            Method: POST
